# Exercise Set 8: Introduction to Web Scraping

*Afternoon, August 16, 2018*

In this Exercise Set we shall practice our webscraping skills utiilizing only basic python. We shall cover variations between static and dynamic pages.

## Exercise Section 8.1: Scraping Jobnet.dk

This exercise you get to practice locating the request that the JavaScript sends to get the job data that it builds the joblistings from. You should use the **>Network Monitor<** tool in your browser.

Furthermore you practice spotting how the pagination is done, without clicking on the next page button, but instead changing a small parameter in the URL.

> **Ex. 8.1.1:** Hit the joblisting webpage here: https://job.jobnet.dk/CV and locate the request that gets the joblisting data using the a tool called the **>Network Monitor<**. To do this open monitor tool and press the search button on the website. Go to the _network_ pane in the monitor and look at the results. Which two _methods_ does your browser use to communicate with the webserver? What does status code 200 mean?
>
>> _Hint:_ The network monitor is launched by pressing ctrl+shift+i in most browsers. Filter by XHR files.

In [ ]:
# [Answer to Ex. 8.1.1 here]

> **Ex. 8.1.2.:** Use the `request` module to collect the first page of job postings and unpack the relevant `json` data into a `pandas` DataFrame.

In [3]:
import requests
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
# [Answer to Ex. 8.1.2 here]
url = "https://job.jobnet.dk/CV/FindWork/Search"
jobdata  = requests.get(url).json()
# response.ok
jobdata.keys()
    #The data consists of 4 dictionairies.

dict_keys(['Expression', 'Facets', 'JobPositionPostings', 'TotalResultCount'])

> **Ex. 8.1.3.:** Store and print the 'TotalResultCount' value for later use. Also create a dataframe from the 'JobPositionPostings' field in the json.

In [41]:
# [Answer to Ex. 8.1.3 here]
TRC = jobdata["TotalResultCount"]
print(TRC)

df = pd.DataFrame(jobdata["JobPositionPostings"])
df #We see the first page of the job postings

16003

,AnonymousEmployer,AssignmentStartDate,AutomatchType,Country,EmploymentType,HasLocationValues,HiringOrgCVR,HiringOrgName,ID,IsExternal,...,UseWorkPlaceAddressForJoblog,Weight,WorkHours,WorkPlaceAbroad,WorkPlaceAddress,WorkPlaceCity,WorkPlaceNotStatic,WorkPlaceOtherAddress,WorkPlacePostalCode,WorkplaceID
0,False,0001-01-01T00:00:00,0,Danmark,,True,32139647,POWER PEOPLE DANMARK ApS,4831880,False,...,False,1.0,Fuldtid,False,,,False,True,,82395
1,False,0001-01-01T00:00:00,0,Danmark,,True,29810788,KRYB-I-LY A/S,4851508,False,...,True,1.0,Fuldtid,False,Kolding Landevej 160,Fredericia,False,False,7000,67143
2,False,0001-01-01T00:00:00,0,Danmark,,True,31544483,Café 18,4861474,False,...,True,1.0,Deltid,False,Krystalgade 18,Rønne,False,False,3700,0
3,False,0001-01-01T00:00:00,0,Danmark,,True,30982894,GG Ejendomsservice v/Mogens van der Goot,4830239,False,...,False,1.0,Fuldtid,False,,,True,False,,92386
4,False,0001-01-01T00:00:00,0,Danmark,,True,38661280,Keeperz ApS,4842917,False,...,True,1.0,Deltid,False,Edvard Thomsens Vej 63,København S,False,False,2300,122935
5,False,0001-01-01T00:00:00,0,Danmark,,True,10691133,Vejlsøhus hotel og konferencecenter,4625721,False,...,True,1.0,Fuldtid,False,Vejlsøvej 051,Silkeborg,False,False,8600,6658
6,False,0001-01-01T00:00:00,0,Danmark,,True,29190658,Region Sjælland,4862975,False,...,False,1.0,Fuldtid,False,,,False,True,,61350
7,False,0001-01-01T00:00:00,0,Danmark,,True,30699599,AGITEK ApS,4833233,False,...,True,1.0,Fuldtid,False,Gammelstrupvej 10,Brædstrup,False,False,8740,82687
8,False,0001-01-01T00:00:00,0,Danmark,,True,32647677,Medarbejderne ApS,4795799,False,...,False,1.0,Fuldtid,False,,,False,True,,113749
9,False,0001-01-01T00:00:00,0,Danmark,,True,29190623,Rigshospitalet,4865460,False,...,True,1.0,Fuldtid,False,Blegdamsvej 9,København Ø,False,False,2100,608
10,False,0001-01-01T00:00:00,0,Danmark,,True,19596915,Copenhagen Business School,4865459,False,...,True,1.0,Fuldtid,False,Solbjerg Plads 3,Frederiksberg,False,False,2000,79401
11,False,0001-01-01T00:00:00,0,Danmark,,True,29556490,Brøndby,4865458,False,...,True,1.0,Fuldtid,False,Brøndby Møllevej 4,Brøndby,False,False,2605,60219
12,False,0001-01-01T00:00:00,0,Danmark,,True,33647921,UGGERHØJ AARHUS A/S,4865457,False,...,True,1.0,Fuldtid,False,Slet Parkvej 2,Højbjerg,False,False,8270,123080
13,False,0001-01-01T00:00:00,0,Danmark,,True,55145016,GEUS,4865455,False,...,True,1.0,Fuldtid,False,Øster Voldgade 10,København K,False,False,1350,77205
14,False,0001-01-01T00:00:00,0,Danmark,,True,10403782,Vestas Wind System A/S,4865454,False,...,True,1.0,Fuldtid,False,Hedeager 42,Aarhus N,False,False,8200,110229
15,False,0001-01-01T00:00:00,0,Danmark,,True,21009539,JYDAN Rengøringsservice,4865452,False,...,False,1.0,Deltid,False,,,False,True,,4856
16,False,0001-01-01T00:00:00,0,Danmark,,True,64942212,Koncern Service og IT,4865451,False,...,True,1.0,Deltid,False,Borups Allé 177,København NV,False,False,2400,76595
17,False,0001-01-01T00:00:00,0,Danmark,,True,64942212,Koncern Service og IT,4865448,False,...,True,1.0,Fuldtid,False,Borups Allé 177,København NV,False,False,2400,76595
18,False,0001-01-01T00:00:00,0,Danmark,,True,33647921,UGGERHØJ AARHUS A/S,4865447,False,...,True,1.0,Fuldtid,False,Slet Parkvej 2,Højbjerg,False,False,8270,123080
19,False,0001-01-01T00:00:00,0,Danmark,,True,31802598,LOBPA,4865446,False,...,False,1.0,Deltid,False,,,False,True,,80514

> **Ex. 8.1.4:** This exercise is about paging the results. We need to understand the websites pagination scheme. Scroll down the webpage and press the next page button. Describe how the parameters of the url changes as you turn the pages.

In [ ]:
# [Answer to Ex. 8.1.4 here]

> **Ex. 8.1.5:** Design a`for` loop using the `range` function that changes this paging parameter in the URL. Use the TotalResultCount parameter from before to define the limits of the range function. Store these urls in a container. 
>
>**Bonus** Change the SortValue parameter from BestMatch to CreationDate, to make the sorting amendable to updating results daily.
>
>> _Hint:_ See that the parameter is an offset and that this relates to the number of results pr. call made.

In [ ]:
# [Answer to Ex. 8.1.5 here]

> **Ex. 8.1.6:** Pick 20 random links using the `choice` function in the `random` module;  collect the links using the `request` module. Also use the `time.sleep()` function to limit the rate of your calls. Make sure to save the links already collected in a `set()` container to avoid having to reload links already collected. ***extra***: monitor the time left to completing the loop by using `tqdm.tqdm()` function.

In [ ]:
# [Answer to Ex. 8.1.6 here]

> **Ex. 8.1.7:** Load all the results into a DataFrame.

In [ ]:
# [Answer to Ex. 8.1.7 here]

## Exercise Section 8.2: Scraping Trustpilot.com
Now for a slightly more elaborate, yet still simple scraping problem. Here we want to scrape trustpilot for user reviews. This data is very nice since it provides free labeled data (rating) to train a machine learning model to understand positive and negative sentiment. 

Here you will practice crawling a website collecting the links to each company review page, and finally locate another behind the scenes JavaScript request that gets the review data in a neat json format.

> **Ex. 8.2.1:** Visit the https://www.trustpilot.com/ website and locate the categories page. From this page you find links to company listings. Get the category page using the `requests` module and extract each link to a specific category page from the HTML. This can be done using the basic python `.split()` string method. Make sure only links within the ***/categories/*** section are kept, checking each string using the ```if 'pattern' in string``` condition. 
>
>> *Hint:* The links are relative. You need to add the domain name
>>
>> *Hint #2:* You will need to convert the page response to a string, using the `.text` property.

In [ ]:
# [Answer to Ex. 8.2.1]

> **Ex. 8.2.2:** Get one of the category section links (any one will do). Write a function to extract the links to the company review pages from the HTML.

In [ ]:
# [Answer to Ex. 8.2.2]

> **Ex. 8.2.3:** Figure out how the pagination is done, by following how the url changes when pressing the **next page**-button to obtain more company listings. Write a function that builds links to paging all the company listing results of each category. This includes parsing the number of subpages of each category and changing the correct parameter in the url.
>
>> *Hint:* Find the maximum number of result pages, right before the next page button and make a loop change the page parameter of the url.

In [ ]:
# [Answer to Ex.8.2.3]

> **Ex. 8.2.4:** Loop through all categories and build the paging links using the above defined function.

In [ ]:
# [Answer to Ex.8.2.4]

> **Ex. 8.2.5:** Randomly pick one of category listing links you have generated, and get the links to the companies listed using the other function defined.

In [ ]:
# [Answer to Ex.8.2.5]

> **Ex. 8.2.6:** Visit one of these links and inspect the **>Network Monitor<** to locate the request that loads the review data. Use the requests module to retrieve this link and unpack the json results to a pandas DataFrame.
>
>> _Hint:_ Look for a request which sends a the link to a file called `jsonId`

In [ ]:
#[Answer to Ex.8.2.6]

Congratulations on coming this far. By now you are almost - still need to figure out how to page the reviews and to find the company ID in the html -, ready to deploy a scraper collecting all reviews on trustpilot. 
If you wanna see just how valuable such data could be visit the follow blogpost: https://blog.openai.com/unsupervised-sentiment-neuron/