# Analyse

In [1]:
import pandas as pd
import time, requests, re
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns 
sns.set(rc={'figure.figsize':(11.7,8.27)})
plt.style.use('ggplot')
# sns.set_style("whitegrid", {'axes.grid' : True})

In [25]:
path = "C:/Users/Naeim.S/Documents/GitHub/GRP33/EXAM/Multi_JobIndexed.xlsx"
# cols = list(range(1,9))
jobindexed = pd.read_excel(path)
jobindexed

,year,area,sektor,jobtype,n_jobtype_area_,n_sektor_area,n_area,n_year,20-64years_area,20-64years_year,n_jobtype_area_pc,n_sektor_area_pc,n_area_pc,n_year_pc,FD_jobtype_area,FD_sektor_area,FD_area,FD_year
0,2007.0,region hovedstaden,handel,boernepasning,234,29369,157867,380597,1021591,3278570,0.000229,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,bud,1097,29369,157867,380597,1021591,3278570,0.001074,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,detailhandel,15574,29369,157867,380597,1021591,3278570,0.015245,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,frisoer,335,29369,157867,380597,1021591,3278570,0.000328,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,hotel,6901,29369,157867,380597,1021591,3278570,0.006755,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,rengoering,2985,29369,157867,380597,1021591,3278570,0.002922,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,service,1790,29369,157867,380597,1021591,3278570,0.001752,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,sikkerhed,580,29369,157867,380597,1021591,3278570,0.000568,0.028748,0.154531,0.116086,NaN,NaN,NaN,NaN
8,NaN,NaN,industri,blik,867,16285,157867,380597,1021591,3278570,0.000849,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,byggeri,1493,16285,157867,380597,1021591,3278570,0.001461,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,elektriker,1487,16285,157867,380597,1021591,3278570,0.001456,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,industri,1806,16285,157867,380597,1021591,3278570,0.001768,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,jern,1495,16285,157867,380597,1021591,3278570,0.001463,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,lager,2892,16285,157867,380597,1021591,3278570,0.002831,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,landbrug,510,16285,157867,380597,1021591,3278570,0.000499,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,maling,354,16285,157867,380597,1021591,3278570,0.000347,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,mekanik,1355,16285,157867,380597,1021591,3278570,0.001326,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,naeringsmiddel,1557,16285,157867,380597,1021591,3278570,0.001524,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,tekstil,246,16285,157867,380597,1021591,3278570,0.000241,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,toemrer,781,16285,157867,380597,1021591,3278570,0.000764,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,traeindustri,125,16285,157867,380597,1021591,3278570,0.000122,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,transport,2764,16285,157867,380597,1021591,3278570,0.002706,0.015941,0.154531,0.116086,NaN,NaN,NaN,NaN
22,NaN,NaN,ingenioer,byggeteknik,2754,10976,157867,380597,1021591,3278570,0.002696,0.010744,0.154531,0.116086,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,elektronik,1590,10976,157867,380597,1021591,3278570,0.001556,0.010744,0.154531,0.116086,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,kemi,3030,10976,157867,380597,1021591,3278570,0.002966,0.010744,0.154531,0.116086,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,maskiningenioer,1943,10976,157867,380597,1021591,3278570,0.001902,0.010744,0.154531,0.116086,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,medicinal,1381,10976,157867,380597,1021591,3278570,0.001352,0.010744,0.154531,0.116086,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,produktionsteknik,1613,10976,157867,380597,1021591,3278570,0.001579,0.010744,0.154531,0.116086,NaN,NaN,NaN,NaN
28,NaN,NaN,it,database,488,16080,157867,380597,1021591,3278570,0.000478,0.015740,0.154531,0.116086,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,internet,805,16080,157867,380597,1021591,3278570,0.000788,0.015740,0.154531,0.116086,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4920,NaN,NaN,NaN,topledelse,44,2204,25973,266462,462645,3341882,0.000095,0.004764,0.056140,0.079734,6.0,-169.0,-368.0,-5600.0
4921,NaN,NaN,NaN,virksomhedsudvikling,0,2204,25973,266462,462645,3341882,0.000000,0.004764,0.056140,0.079734,0.0,-169.0,-368.0,-5600.0
4922,NaN,NaN,oevrige,elev,378,2650,25973,266462,462645,3341882,0.000817,0.005728,0.056140,0.079734,83.0,361.0,-368.0,-5600.0
4923,NaN,NaN,NaN,forsvar,0,2650,25973,266462,462645,3341882,0.000000,0.005728,0.056140,0.079734,0.0,361.0,-368.0,-5600.0
4924,NaN,NaN,NaN,frivilligt,849,2650,25973,266462,462645,3341882,0.001835,0.005728,0.056140,0.079734,104.0,361.0,-368.0,-5600.0
4925,NaN,NaN,NaN,kurseroevrige,2,2650,25973,266462,462645,3341882,0.000004,0.005728,0.056140,0.079734,-2.0,361.0,-368.0,-5600.0
4926,NaN,NaN,NaN,oevrige,868,2650,25973,266462,462645,3341882,0.001876,0.005728,0.056140,0.079734,57.0,361.0,-368.0,-5600.0
4927,NaN,NaN,NaN,student,400,2650,25973,266462,462645,3341882,0.000865,0.005728,0.056140,0.079734,131.0,361.0,-368.0,-5600.0
4928,NaN,NaN,NaN,studiepraktik,52,2650,25973,266462,462645,3341882,0.000112,0.005728,0.056140,0.079734,15.0,361.0,-368.0,-5600.0
4929,NaN,NaN,salg,design,24,2372,25973,266462,462645,3341882,0.000052,0.005127,0.056140,0.079734,3.0,-155.0,-368.0,-5600.0
4930,NaN,NaN,NaN,franchise,42,2372,25973,266462,462645,3341882,0.000091,0.005127,0.056140,0.079734,23.0,-155.0,-368.0,-5600.0
4931,NaN,NaN,NaN,grafisk,39,2372,25973,266462,462645,3341882,0.000084,0.005127,0.056140,0.079734,-3.0,-155.0,-368.0,-5600.0
4932,NaN,NaN,NaN,kommunikation,177,2372,25973,266462,462645,3341882,0.000383,0.005127,0.056140,0.079734,58.0,-155.0,-368.0,-5600.0
4933,NaN,NaN,NaN,kultur,208,2372,25973,266462,462645,3341882,0.000450,0.005127,0.056140,0.079734,-10.0,-155.0,-368.0,-5600.0
4934,NaN,NaN,NaN,marketing,187,2372,25973,266462,462645,3341882,0.000404,0.005127,0.056140,0.079734,14.0,-155.0,-368.0,-5600.0
4935,NaN,NaN,NaN,salg,1427,2372,25973,266462,462645,3341882,0.003084,0.005127,0.056140,0.079734,-184.0,-155.0,-368.0,-5600.0
4936,NaN,NaN,NaN,salgskurser,4,2372,25973,266462,462645,3341882,0.000009,0.005127,0.056140,0.079734,0.0,-155.0,-368.0,-5600.0
4937,NaN,NaN,NaN,telemarketing,50,2372,25973,266462,462645,3341882,0.000108,0.005127,0.056140,0.079734,-63.0,-155.0,-368.0,-5600.0
4938,NaN,NaN,social,laege,676,6330,25973,266462,462645,3341882,0.001461,0.013682,0.056140,0.079734,-126.0,-10.0,-368.0,-5600.0
4939,NaN,NaN,NaN,laegesekretaer,168,6330,25973,266462,462645,3341882,0.000363,0.013682,0.056140,0.079734,-92.0,-10.0,-368.0,-5600.0
4940,NaN,NaN,NaN,pleje,2431,6330,25973,266462,462645,3341882,0.005255,0.013682,0.056140,0.079734,292.0,-10.0,-368.0,-5600.0
4941,NaN,NaN,NaN,psykologi,197,6330,25973,266462,462645,3341882,0.000426,0.013682,0.056140,0.079734,21.0,-10.0,-368.0,-5600.0
4942,NaN,NaN,NaN,socialraadgivning,487,6330,25973,266462,462645,3341882,0.001053,0.013682,0.056140,0.079734,52.0,-10.0,-368.0,-5600.0
4943,NaN,NaN,NaN,tandlaege,232,6330,25973,266462,462645,3341882,0.000501,0.013682,0.056140,0.079734,21.0,-10.0,-368.0,-5600.0
4944,NaN,NaN,NaN,teknisksundhed,77,6330,25973,266462,462645,3341882,0.000166,0.013682,0.056140,0.079734,12.0,-10.0,-368.0,-5600.0
4945,NaN,NaN,NaN,terapi,360,6330,25973,266462,462645,3341882,0.000778,0.013682,0.056140,0.079734,-3.0,-10.0,-368.0,-5600.0
4946,NaN,NaN,undervisning,bibliotek,40,4499,25973,266462,462645,3341882,0.000086,0.009725,0.056140,0.079734,17.0,231.0,-368.0,-5600.0
4947,NaN,NaN,NaN,forskning,594,4499,25973,266462,462645,3341882,0.001284,0.009725,0.056140,0.079734,131.0,231.0,-368.0,-5600.0
4948,NaN,NaN,NaN,laerer,1475,4499,25973,266462,462645,3341882,0.003188,0.009725,0.056140,0.079734,-156.0,231.0,-368.0,-5600.0
4949,NaN,NaN,NaN,paedagog,2197,4499,25973,266462,462645,3341882,0.004749,0.009725,0.056140,0.079734,236.0,231.0,-368.0,-5600.0

In [24]:
#Creating the First-Differences by each group:
# jobindexed.FD_area = jobindexed.n_area.groupby(level=[0,1]).diff()
jobindexed["FD_area"] = jobindexed["n_area"].groupby(level=["jobtype"]).diff(1)
jobindexed[["n_area", "FD_area"]].query("jobtype == 'database'")

                                         n_area   FD_area
year area               sektor jobtype
2007 region hovedstaden it     database  157867       NaN
     region syddanmark  it     database   78473  -79394.0
     region-midtjylland it     database   80746    2273.0
     region-nordjylland it     database   26736  -54010.0
     region-sjaelland   it     database   38163   11427.0
2008 region hovedstaden it     database  129930   91767.0
     region syddanmark  it     database   60879  -69051.0
     region-midtjylland it     database   66756    5877.0
     region-nordjylland it     database   23530  -43226.0
     region-sjaelland   it     database   32955    9425.0
2009 region hovedstaden it     database   68902   35947.0
     region syddanmark  it     database   31271  -37631.0
     region-midtjylland it     database   35370    4099.0
     region-nordjylland it     database   12958  -22412.0
     region-sjaelland   it     database   16937    3979.0
2010 region hovedstaden it     database   71235   54298.0
     region syddanmark  it     database   31596  -39639.0
     region-midtjylland it     database   36764    5168.0
     region-nordjylland it     database   13181  -23583.0
     region-sjaelland   it     database   13767     586.0
2011 region hovedstaden it     database   84091   70324.0
     region syddanmark  it     database   33230  -50861.0
     region-midtjylland it     database   36632    3402.0
     region-nordjylland it     database   12995  -23637.0
     region-sjaelland   it     database   15338    2343.0
2012 region hovedstaden it     database   88485   73147.0
     region syddanmark  it     database   34328  -54157.0
     region-midtjylland it     database   38796    4468.0
     region-nordjylland it     database   15053  -23743.0
     region-sjaelland   it     database   17618    2565.0
2013 region hovedstaden it     database   93116   75498.0
     region syddanmark  it     database   34399  -58717.0
     region-midtjylland it     database   40778    6379.0
     region-nordjylland it     database   14887  -25891.0
     region-sjaelland   it     database   18777    3890.0
2014 region hovedstaden it     database  116016   97239.0
     region syddanmark  it     database   41647  -74369.0
     region-midtjylland it     database   46742    5095.0
     region-nordjylland it     database   16927  -29815.0
     region-sjaelland   it     database   23507    6580.0
2015 region hovedstaden it     database  122488   98981.0
     region syddanmark  it     database   43432  -79056.0
     region-midtjylland it     database   50044    6612.0
     region-nordjylland it     database   18660  -31384.0
     region-sjaelland   it     database   24180    5520.0
2016 region hovedstaden it     database  124975  100795.0
     region syddanmark  it     database   46105  -78870.0
     region-midtjylland it     database   55935    9830.0
     region-nordjylland it     database   21528  -34407.0
     region-sjaelland   it     database   26341    4813.0
2017 region hovedstaden it     database  124641   98300.0
     region syddanmark  it     database   48006  -76635.0
     region-midtjylland it     database   56804    8798.0
     region-nordjylland it     database   19942  -36862.0
     region-sjaelland   it     database   25973    6031.0

In [223]:
jobindexed.xs(key="laege", level=3)

                                n_jobtype_area_  n_sektor_area  n_area  \
year area               sektor
2007 region hovedstaden social             2018          18193  157867
     region syddanmark  social             1023          12128   78473
     region-midtjylland social             1059          12003   80746
     region-nordjylland social              376           4551   26736
     region-sjaelland   social              587           6491   38163
2008 region hovedstaden social             1538          15023  129930
     region syddanmark  social              858           9974   60879
     region-midtjylland social              918          10432   66756
     region-nordjylland social              388           4483   23530
     region-sjaelland   social              801           7308   32955
2009 region hovedstaden social             1376          10537   68902
     region syddanmark  social              865           6734   31271
     region-midtjylland social              842           7580   35370
     region-nordjylland social              354           3176   12958
     region-sjaelland   social              554           4492   16937
2010 region hovedstaden social             1080           7075   71235
     region syddanmark  social              957           5444   31596
     region-midtjylland social              915           5583   36764
     region-nordjylland social              300           2561   13181
     region-sjaelland   social              398           2611   13767
2011 region hovedstaden social             1294           7978   84091
     region syddanmark  social             1335           5907   33230
     region-midtjylland social             1037           4590   36632
     region-nordjylland social              349           2021   12995
     region-sjaelland   social              506           3179   15338
2012 region hovedstaden social             1502          10889   88485
     region syddanmark  social             1191           6196   34328
     region-midtjylland social             1025           5864   38796
     region-nordjylland social              451           2668   15053
     region-sjaelland   social              614           3916   17618
2013 region hovedstaden social             1610          12719   93116
     region syddanmark  social              942           6140   34399
     region-midtjylland social             1013           6464   40778
     region-nordjylland social              457           2788   14887
     region-sjaelland   social              600           4400   18777
2014 region hovedstaden social             1844          15963  116016
     region syddanmark  social             1089           7354   41647
     region-midtjylland social             1212           7807   46742
     region-nordjylland social              491           3185   16927
     region-sjaelland   social              797           5948   23507
2015 region hovedstaden social             2203          17119  122488
     region syddanmark  social              894           6882   43432
     region-midtjylland social             1124           7874   50044
     region-nordjylland social              503           3378   18660
     region-sjaelland   social              788           5624   24180
2016 region hovedstaden social             1877          17462  124975
     region syddanmark  social              860           8186   46105
     region-midtjylland social             1133           9058   55935
     region-nordjylland social              461           3974   21528
     region-sjaelland   social              802           6340   26341
2017 region hovedstaden social             1730          18619  124641
     region syddanmark  social              768           8712   48006
     region-midtjylland social              809           8902   56804
     region-nordjylland social              349           3424   19942
     region-sjaelland   social              676           6330   25973

                                n_year  20-64years_area  20-64years_year  \
year area               sektor
2007 region hovedstaden social  380597          1021591          3278570
     region syddanmark  social  380597           697412          3278570
     region-midtjylland social  380597           739328          3278570
     region-nordjylland social  380597           340088          3278570
     region-sjaelland   social  380597           480151          3278570
2008 region hovedstaden social  312907          1028062          3285407
     region syddanmark  social  312907           697102          3285407
     region-midtjylland social  312907           742328          3285407
     region-nordjylland social  312907           339850          3285407
     region-sjaelland   social  312907           478065          3285407
2009 region hovedstaden social  167084          1035021          3283177
     region syddanmark  social  167084           693620          3283177
     region-midtjylland social  167084           743600          3283177
     region-nordjylland social  167084           337476          3283177
     region-sjaelland   social  167084           473460          3283177
2010 region hovedstaden social  172785          1042178          3278253
     region syddanmark  social  172785           689196          3278253
     region-midtjylland social  172785           743163          3278253
     region-nordjylland social  172785           335379          3278253
     region-sjaelland   social  172785           468337          3278253
2011 region hovedstaden social  193597          1046710          3270291
     region syddanmark  social  193597           684945          3270291
     region-midtjylland social  193597           742150          3270291
     region-nordjylland social  193597           334314          3270291
     region-sjaelland   social  193597           462172          3270291
2012 region hovedstaden social  231999          1052587          3267131
     region syddanmark  social  231999           681901          3267131
     region-midtjylland social  231999           742072          3267131
     region-nordjylland social  231999           333001          3267131
     region-sjaelland   social  231999           457570          3267131
2013 region hovedstaden social  224151          1062482          3274970
     region syddanmark  social  224151           680414          3274970
     region-midtjylland social  224151           743860          3274970
     region-nordjylland social  224151           332897          3274970
     region-sjaelland   social  224151           455317          3274970
2014 region hovedstaden social  255002          1074591          3290630
     region syddanmark  social  255002           681584          3290630
     region-midtjylland social  255002           745341          3290630
     region-nordjylland social  255002           333298          3290630
     region-sjaelland   social  255002           455816          3290630
2015 region hovedstaden social  307829          1088448          3317615
     region syddanmark  social  307829           684358          3317615
     region-midtjylland social  307829           750320          3317615
     region-nordjylland social  307829           334902          3317615
     region-sjaelland   social  307829           459587          3317615
2016 region hovedstaden social  272062          1101004          3341882
     region syddanmark  social  272062           687287          3341882
     region-midtjylland social  272062           755612          3341882
     region-nordjylland social  272062           335951          3341882
     region-sjaelland   social  272062           462028          3341882
2017 region hovedstaden social  266462          1110938          3341882
     region syddanmark  social  266462           688936          3341882
     region-midtjylland social  266462           761137          3341882
     region-nordjylland social  266462           336178          3341882
     region-sjaelland   social  266462           462645          3341882

                                n_jobtype_area_pc  n_sektor_area_pc  \
year area               sektor
2007 region hovedstaden social           0.001975          0.017808
     region syddanmark  social           0.001467          0.017390
     region-midtjylland social           0.001432          0.016235
     region-nordjylland social           0.001106          0.013382
     region-sjaelland   social           0.001223          0.013519
2008 region hovedstaden social           0.001496          0.014613
     region syddanmark  social           0.001231          0.014308
     region-midtjylland social           0.001237          0.014053
     region-nordjylland social           0.001142          0.013191
     region-sjaelland   social           0.001676          0.015287
2009 region hovedstaden social           0.001329          0.010180
     region syddanmark  social           0.001247          0.009708
     region-midtjylland social           0.001132          0.010194
     region-nordjylland social           0.001049          0.009411
     region-sjaelland   social           0.001170          0.009488
2010 region hovedstaden social           0.001036          0.006789
     region syddanmark  social           0.001389          0.007899
     region-midtjylland social           0.001231          0.007512
     region-nordjylland social           0.000895          0.007636
     region-sjaelland   social           0.000850          0.005575
2011 region hovedstaden social           0.001236          0.007622
     region syddanmark  social           0.001949          0.008624
     region-midtjylland social           0.001397          0.006185
     region-nordjylland social           0.001044          0.006045
     region-sjaelland   social           0.001095          0.006878
2012 region hovedstaden social           0.001427          0.010345
     region syddanmark  social           0.001747          0.009086
     region-midtjylland social           0.001381          0.007902
     region-nordjylland social           0.001354          0.008012
     region-sjaelland   social           0.001342          0.008558
2013 region hovedstaden social           0.001515          0.011971
     region syddanmark  social           0.001384          0.009024
     region-midtjylland social           0.001362          0.008690
     region-nordjylland social           0.001373          0.008375
     region-sjaelland   social           0.001318          0.009664
2014 region hovedstaden social           0.001716          0.014855
     region syddanmark  social           0.001598          0.010790
     region-midtjylland social           0.001626          0.010474
     region-nordjylland social           0.001473          0.009556
     region-sjaelland   social           0.001749          0.013049
2015 region hovedstaden social           0.002024          0.015728
     region syddanmark  social           0.001306          0.010056
     region-midtjylland social           0.001498          0.010494
     region-nordjylland social           0.001502          0.010087
     region-sjaelland   social           0.001715          0.012237
2016 region hovedstaden social           0.001705          0.015860
     region syddanmark  social           0.001251          0.011911
     region-midtjylland social           0.001499          0.011988
     region-nordjylland social           0.001372          0.011829
     region-sjaelland   social           0.001736          0.013722
2017 region hovedstaden social           0.001557          0.016760
     region syddanmark  social           0.001115          0.012646
     region-midtjylland social           0.001063          0.011696
     region-nordjylland social           0.001038          0.010185
     region-sjaelland   social           0.001461          0.013682

                                n_area_pc  n_year_pc
year area               sektor
2007 region hovedstaden social   0.154531   0.116086
     region syddanmark  social   0.112520   0.116086
     region-midtjylland social   0.109215   0.116086
     region-nordjylland social   0.078615   0.116086
     region-sjaelland   social   0.079481   0.116086
2008 region hovedstaden social   0.126383   0.095241
     region syddanmark  social   0.087332   0.095241
     region-midtjylland social   0.089928   0.095241
     region-nordjylland social   0.069236   0.095241
     region-sjaelland   social   0.068934   0.095241
2009 region hovedstaden social   0.066571   0.050891
     region syddanmark  social   0.045084   0.050891
     region-midtjylland social   0.047566   0.050891
     region-nordjylland social   0.038397   0.050891
     region-sjaelland   social   0.035773   0.050891
2010 region hovedstaden social   0.068352   0.052706
     region syddanmark  social   0.045845   0.052706
     region-midtjylland social   0.049470   0.052706
     region-nordjylland social   0.039302   0.052706
     region-sjaelland   social   0.029395   0.052706
2011 region hovedstaden social   0.080338   0.059199
     region syddanmark  social   0.048515   0.059199
     region-midtjylland social   0.049359   0.059199
     region-nordjylland social   0.038871   0.059199
     region-sjaelland   social   0.033187   0.059199
2012 region hovedstaden social   0.084064   0.071010
     region syddanmark  social   0.050342   0.071010
     region-midtjylland social   0.052281   0.071010
     region-nordjylland social   0.045204   0.071010
     region-sjaelland   social   0.038503   0.071010
2013 region hovedstaden social   0.087640   0.068444
     region syddanmark  social   0.050556   0.068444
     region-midtjylland social   0.054819   0.068444
     region-nordjylland social   0.044720   0.068444
     region-sjaelland   social   0.041239   0.068444
2014 region hovedstaden social   0.107963   0.077493
     region syddanmark  social   0.061103   0.077493
     region-midtjylland social   0.062712   0.077493
     region-nordjylland social   0.050786   0.077493
     region-sjaelland   social   0.051571   0.077493
2015 region hovedstaden social   0.112535   0.092786
     region syddanmark  social   0.063464   0.092786
     region-midtjylland social   0.066697   0.092786
     region-nordjylland social   0.055718   0.092786
     region-sjaelland   social   0.052612   0.092786
2016 region hovedstaden social   0.113510   0.081410
     region syddanmark  social   0.067083   0.081410
     region-midtjylland social   0.074026   0.081410
     region-nordjylland social   0.064081   0.081410
     region-sjaelland   social   0.057012   0.081410
2017 region hovedstaden social   0.112194   0.079734
     region syddanmark  social   0.069681   0.079734
     region-midtjylland social   0.074630   0.079734
     region-nordjylland social   0.059320   0.079734
     region-sjaelland   social   0.056140   0.079734